#!/bin/bash

RAYON_NUM_THREADS=64 cargo run --release &
echo "      date     time $(free -g | grep total | sed -E 's/^    (.*)/\1/g')"
while sleep 1; do
	echo "$(date '+%Y-%m-%d %H:%M:%S') $(free -g | grep Mem: | sed 's/Mem://g')"
done